{% set name = "napari-matplotlib" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 25326720c5ae2e3194a8fd4e77332d7902b5efd8b6219e9e7c8f943f07bce281

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - matplotlib-base
    - napari >=0.5
    - numpy
    - python >={{ python_min }}
    - qtpy
    - tinycss2

test:
  imports:
    - napari_matplotlib
  commands:
    - python -c 'from napari_matplotlib import __version__;print(__version__)'
    - pip list
    - pip check
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://github.com/matplotlib/napari-matplotlib
  summary: A plugin to use Matplotlib with napari
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/matplotlib/napari-matplotlib

extra:
  recipe-maintainers:
    - dstansby
    - goanpeca
    - jaimergp
